"""Regenerate universe.txt from the S&P 500 + Nasdaq-100 constituents (Wikipedia).

A maintenance tool, not part of the scanner runtime — run it on demand to refresh
the universe:

    python scripts/build_universe.py

Tickers are upper-cased, dots -> dashes (BRK.B -> BRK-B, yfinance style), merged and
de-duplicated, and written sorted so diffs stay clean. Needs ``lxml`` + ``requests``.

Survivorship-bias note (SPEC §4.1): this reflects *today's* constituents — correct
for live scanning, but a future backtest must use a point-in-time universe instead.
"""
from __future__ import annotations

import io
from pathlib import Path

import pandas as pd
import requests

_SP500_URL = "https://en.wikipedia.org/wiki/List_of_S%26P_500_companies"
_NDX_URL = "https://en.wikipedia.org/wiki/Nasdaq-100"
_SYMBOL_COLUMNS = ("Symbol", "Ticker")
_HEADERS = {"User-Agent": "Mozilla/5.0 (trade-sniffer universe builder)"}
_UNIVERSE_PATH = Path(__file__).resolve().parent.parent / "universe.txt"


def _fetch_symbols(url: str) -> list[str]:
    """Return the ticker column from the first Wikipedia table that has one."""
    html = requests.get(url, headers=_HEADERS, timeout=30).text
    for table in pd.read_html(io.StringIO(html)):
        for column in _SYMBOL_COLUMNS:
            if column in table.columns:
                return [_normalize(value) for value in table[column].dropna()]
    raise SystemExit(f"No symbol/ticker column found in any table at {url}")


def _normalize(symbol: str) -> str:
    # Wikipedia uses BRK.B; yfinance/TradingView use BRK-B.
    return str(symbol).strip().upper().replace(".", "-")


def main() -> None:
    symbols = _fetch_symbols(_SP500_URL) + _fetch_symbols(_NDX_URL)
    tickers = sorted({s for s in symbols if s and s != "NAN"})

    header = (
        "# Ticker universe — one bare ticker per line (no exchange prefix; resolved at fetch time).\n"
        "# Generated by scripts/build_universe.py from S&P 500 + Nasdaq-100 (Wikipedia).\n"
        "# Edit by hand or re-run the script to refresh. The liquidity gate still filters at\n"
        "# scan time; SPY is always fetched as the RS reference (no need to list it).\n\n"
    )
    _UNIVERSE_PATH.write_text(header + "\n".join(tickers) + "\n", encoding="utf-8")
    print(f"Wrote {len(tickers)} tickers to {_UNIVERSE_PATH}")


if __name__ == "__main__":
    main()
