"""Regenerate universe.txt from the S&P 500 + Nasdaq-100 constituents (Wikipedia).

A maintenance tool, not part of the scanner runtime — run it on demand to refresh
the universe:

    python scripts/build_universe.py

Tickers are upper-cased, dots -> dashes (BRK.B -> BRK-B, yfinance style), merged and
de-duplicated, and written sorted so diffs stay clean. Needs ``lxml`` + ``requests``.

**Manual additions are preserved:** any lines below the ``# --- Manual additions`` marker
(custom tickers not in the indices, e.g. nuclear/uranium names) are carried across re-runs
verbatim, and excluded from the generated set so a name that later graduates into an index
doesn't get listed twice.

Survivorship-bias note (SPEC §4.1): this reflects *today's* constituents — correct
for live scanning, but a future backtest must use a point-in-time universe instead.
"""
from __future__ import annotations

import io
from pathlib import Path

import pandas as pd
import requests

_SP500_URL = "https://en.wikipedia.org/wiki/List_of_S%26P_500_companies"
_NDX_URL = "https://en.wikipedia.org/wiki/Nasdaq-100"
_SYMBOL_COLUMNS = ("Symbol", "Ticker")
_HEADERS = {"User-Agent": "Mozilla/5.0 (trade-sniffer universe builder)"}
_UNIVERSE_PATH = Path(__file__).resolve().parent.parent / "universe.txt"
# Lines from this marker to EOF are user-maintained and preserved across regenerations.
_MANUAL_MARKER = "# --- Manual additions"
_HEADER = (
    "# Ticker universe — one bare ticker per line (no exchange prefix; resolved at fetch time).\n"
    "# Generated by scripts/build_universe.py from S&P 500 + Nasdaq-100 (Wikipedia).\n"
    "# Edit by hand or re-run the script to refresh. Lines below the \"Manual additions\" marker\n"
    "# are PRESERVED across re-runs. The liquidity gate still filters at scan time; SPY is\n"
    "# always fetched as the RS reference (no need to list it).\n\n"
)


def _fetch_symbols(url: str) -> list[str]:
    """Return the ticker column from the first Wikipedia table that has one."""
    html = requests.get(url, headers=_HEADERS, timeout=30).text
    for table in pd.read_html(io.StringIO(html)):
        for column in _SYMBOL_COLUMNS:
            if column in table.columns:
                return [_normalize(value) for value in table[column].dropna()]
    raise SystemExit(f"No symbol/ticker column found in any table at {url}")


def _normalize(symbol: str) -> str:
    # Wikipedia uses BRK.B; yfinance/TradingView use BRK-B.
    return str(symbol).strip().upper().replace(".", "-")


def _manual_block(existing_text: str) -> str:
    """The manual section (the marker line → EOF) from an existing universe file, or ``""``.
    Preserved verbatim across re-runs so hand-added tickers + their comments survive."""
    lines = existing_text.splitlines()
    for i, line in enumerate(lines):
        if line.startswith(_MANUAL_MARKER):
            return "\n".join(lines[i:]).rstrip()
    return ""


def _tickers_in(block: str) -> set[str]:
    """Bare tickers in a block (non-comment, non-blank lines)."""
    return {ln.strip() for ln in block.splitlines() if ln.strip() and not ln.lstrip().startswith("#")}


def compose_universe(symbols: list[str], existing_text: str) -> str:
    """Build the full universe.txt text: header + generated tickers (sorted, with any that are
    in the preserved manual block removed to avoid duplicates) + the manual block verbatim.

    Pure (no I/O) so it's unit-testable without hitting the network or the filesystem."""
    block = _manual_block(existing_text)
    manual = _tickers_in(block)
    generated = sorted({s for s in symbols if s and s != "NAN"} - manual)
    text = _HEADER + "\n".join(generated) + "\n"
    if block:
        text += "\n" + block + "\n"
    return text


def main() -> None:
    symbols = _fetch_symbols(_SP500_URL) + _fetch_symbols(_NDX_URL)
    existing = _UNIVERSE_PATH.read_text(encoding="utf-8") if _UNIVERSE_PATH.exists() else ""
    _UNIVERSE_PATH.write_text(compose_universe(symbols, existing), encoding="utf-8")
    n_manual = len(_tickers_in(_manual_block(existing)))
    print(f"Wrote universe.txt to {_UNIVERSE_PATH} ({n_manual} manual ticker(s) preserved)")


if __name__ == "__main__":
    main()
